interface Language { chinese: string; english: string, japanese: string };

export const modelList = [
  'claude-3-opus-20240229',
  'claude-3-sonnet-20240229',
  'claude-3-haiku-20240307',
  'glm-4v',
  'gpt-4-turbo',
  'gemini-1.5-pro',
  'qwen-vl-max',
  'qwen-vl-plus',
  'claude-3-5-sonnet-20240620',
  'step-1v-32k',
  'step-1v-8k',
  'yi-vision',
  'gemini-1.5-flash-001',
  'gpt-4o-mini-2024-07-18',
  'gemini-1.5-pro-exp-0801',
  'gpt-4o-2024-08-06',
  'chatgpt-4o-latest',
  'glm-4v-plus',
]

export const LANG = { "en-US": 'english', "zh-CN": 'chinese', "ja-JP": 'japanese' }

export const LANG_SHORT = { "en": 'english', "zh": 'chinese', "ja": 'japanese' }


export const HEADER_TITLE: Language = { chinese: 'AI 提示词专家', english: 'AI prompt word expert', japanese: 'AIプロンプトワード専門家' };

export const LANGUAGE_LIBRARY = {
  "chinese": {
    '记住分享码': '记住分享码',
    '重新登录': '重新登录',
    '确认': '确认',
    '更多请访问': '更多请访问',
    '请输入分享码': '请输入分享码',
    '创建者开启了验证, 请在下方填入分享码': '创建者开启了验证, 请在下方填入分享码',
    '需要分享码': '需要分享码',
    '搜索工具已删除': '搜索工具已删除',
    '搜索工具已禁用': '搜索工具已禁用',
    '分享码错误': '分享码错误',
    '未知错误': '未知错误',
    '网络错误': '网络错误',
    '请联系': '请联系',
    '客服': '客服',
    '没有设置当前版本': '没有设置当前版本',
    '只能重新生成第一个版本': '只能重新生成第一个版本',
    '没有设置父版本': '没有设置父版本',
    '版本历史记录无效': '版本历史记录无效',
    'AI网页复制器': 'AI网页复制器',
    '生成': '生成',
    'OpenAI API 目前已关闭, 30 分钟或更晚后重试, 我们对不便表示抱歉': 'OpenAI API 目前已关闭, 30 分钟或更晚后重试, 我们对不便表示抱歉',
    '从视频生成代码可能需要 3-4 分钟, 我们进行多次传递以获得最佳结果, 请耐心等待': '从视频生成代码可能需要 3-4 分钟, 我们进行多次传递以获得最佳结果, 请耐心等待',
    '取消': '取消',
    '包括当前版本的屏幕截图吗？': '包括当前版本的屏幕截图吗？',
    '更新': '更新',
    '重新生成': '重新生成',
    '原始视频': '原始视频',
    '原始截图': '原始截图',
    '告诉AI要改变什么': '告诉AI要改变什么',
    '重置': '重置',
    '下载': '下载',
    '桌面端': '桌面端',
    '移动端': '移动端',
    '代码': '代码',
    '选择': '选择',
    '账户凭证丢失，请': '账户凭证丢失，请',
    '该工具已禁用/删除': '该工具已禁用/删除',
    '网络错误，请稍后重试': '网络错误，请稍后重试',
    '账户余额不足，创建属于自己的工具': '账户余额不足，创建属于自己的工具',
    '账户总额度已达上限': '账户总额度已达上限',
    '账户日额度已达上限': '账户日额度已达上限',
    '当前无可用通道': '当前无可用通道',
    '不支持当前API功能': '不支持当前API功能',
    '代码生成已取消': '代码生成已取消',
    '代码生成出错': '代码生成出错',
    '请输入代码': '请输入代码',
    '请选择你的HTML结构': '请选择你的HTML结构',
    '导入代码': '导入代码',
    '输入HTML代码': '输入HTML代码',
    '确保您导入的代码是有效的 HTML': '确保您导入的代码是有效的 HTML',
    '结构': '结构',
    '导入': '导入',
    '编码中...': '编码中...',
    '获得更好结果的技巧': '获得更好结果的技巧',
    '关于AI网页复制器': '关于AI网页复制器',
    '设置': '设置',
    'DALL-E 占位符图像生成': 'DALL-E 占位符图像生成',
    '它更有趣, 但如果你想省钱, 就关掉它': '它更有趣, 但如果你想省钱, 就关掉它',
    '代码编辑器主题 - 需要刷新页面才能更新': '代码编辑器主题 - 需要刷新页面才能更新',
    '保存': '保存',
    '已复制至剪切板': '已复制至剪切板',
    '复制代码': '复制代码',
    '打开': '打开',
    '将屏幕截图拖放到此处或单击上传': '将屏幕截图拖放到此处或单击上传',
    '新!': '新!',
    '上传屏幕录像': '上传屏幕录像',
    'AI模型': 'AI模型',
    '版本': '版本',
    '请等待代码生成完成后再查看旧版本': '请等待代码生成完成后再查看旧版本',
    '父版本': '父版本',
    '切换': '切换',
    '该免费工具在本小时的额度已达上限,请访问': '该免费工具在本小时的额度已达上限,请访问',
    '生成属于自己的工具': '生成属于自己的工具',
    '新加坡Prompt大赛冠军框架,一键将简单任务拆解,分析,并生成结构化提示词。': '新加坡Prompt大赛冠军框架,一键将简单任务拆解,分析,并生成结构化提示词。',
    '根据LangGPT框架优化,将简单任务拆解成复杂的工作流,并生成结构化提示词。': '根据LangGPT框架优化,将简单任务拆解成复杂的工作流,并生成结构化提示词。',
    '将用户输入的画面描述拆解为镜头、光线、主体、背景、风格和氛围六个要素，进行补充和完善，生成高质量的绘画提示词。': '将用户输入的画面描述拆解为镜头、光线、主体、背景、风格和氛围六个要素，进行补充和完善，生成高质量的绘画提示词。',
    '清华大学和上海AI实验室提出的提示词优化方法。': '清华大学和上海AI实验室提出的提示词优化方法。',
    '通过模拟解决问题的思考过程来提高模型生成内容的质量和相关性。': '通过模拟解决问题的思考过程来提高模型生成内容的质量和相关性。',
    'Google Deepmind最新研究，变分规划提升Prompt。': 'Google Deepmind最新研究，变分规划提升Prompt。',
    '利用马尔可夫决策过程进行提示词优化。': '利用马尔可夫决策过程进行提示词优化。',
    '卡内基梅隆大学最新研究，让提示词递归内省。': '卡内基梅隆大学最新研究，让提示词递归内省。',
    '微软最新的研究，通过自动优化你的指令数据集来提升你的Prompt能力。': '微软最新的研究，通过自动优化你的指令数据集来提升你的Prompt能力。',
    '请输入内容！': '请输入内容！',
    '请输入需要修改的点！': '请输入需要修改的点！',
    '复制成功 !': '复制成功 !',
    '请输入您的想法，例如：太空人骑着彩虹独角兽': '请输入您的想法，例如：太空人骑着彩虹独角兽',
    '请输入您的任务,例如:写一篇宣传AI的小红书': '请输入您的任务,例如:写一篇宣传AI的小红书',
    '模仿o1遵循结构化思考、分步推理、持续反思和调整策略的提示词': '模仿o1遵循结构化思考、分步推理、持续反思和调整策略的提示词',
    '正在生成，请耐心等待...': '正在生成，请耐心等待...',
    'CO-STAR结构': 'CO-STAR结构',
    'CRISPE结构': 'CRISPE结构',
    'AI绘画提示词': 'AI绘画提示词',
    'Meta Prompting': 'Meta Prompting',
    'CoT思维链': 'CoT思维链',
    '变分法': '变分法',
    'Q*': 'Q*',
    'RISE': 'RISE',
    'o1-style': 'o1-style',
    '微软优化法': '微软优化法',
    '回退': '回退',
    '请提出需要修改的点': '请提出需要修改的点',
    '修改中...': '修改中...',
    '修改': '修改',
    '复制': '复制',
    '正在测试中，请耐心等待...': '正在测试中，请耐心等待...',
    '测试': '测试',
    '测试模型为': '测试模型为',
    '选择一张图片': '选择一张图片',
    '或': '或',
    '上传图片大小不能超过5M': '上传图片大小不能超过5M',
    '暂不支持当前图片格式': '暂不支持当前图片格式',
    '自定义': '自定义',
    '自定义提示词优化指令': '自定义提示词优化指令',
    '编辑提示词优化指令': '编辑提示词优化指令',
    '提示词优化指令': '提示词优化指令',
    '请输入提示词优化指令': '请输入提示词优化指令',
    '你可以使用“{input}”作为占位符替换输入的任务，如果没有指定，则输入的任务会被追加到末尾。': '你可以使用“{input}”作为占位符替换输入的任务，如果没有指定，则输入的任务会被追加到末尾。',
    '提示词优化指令为空，请先编辑优化指令！': '提示词优化指令为空，请先编辑优化指令！',
    'OpenAI优化法': 'OpenAI优化法',
    'OpenAI官方开源的提示词优化方法': 'OpenAI官方开源的提示词优化方法',
    "Claude优化法": 'Claude优化法',
    "Claude官方开源的提示词优化方法": "Claude官方开源的提示词优化方法"
  },
  "english": {
    '记住分享码': 'Remember the sharing code',
    '重新登录': 'Relogin',
    '确认': 'Confirm',
    '更多请访问': 'For more information, please visit',
    '请输入分享码': 'Please enter the sharing code',
    '创建者开启了验证, 请在下方填入分享码': 'The creator has enabled verification, please enter the sharing code below',
    '需要分享码': 'Sharing code required',
    '搜索工具已删除': 'Search tool has been deleted',
    '搜索工具已禁用': 'Search tool has been disabled',
    '分享码错误': 'Invalid sharing code',
    '未知错误': 'unknown error',
    '网络错误': 'network error',
    '请联系': 'Please contact',
    '客服': 'customer service',
    '没有设置当前版本': 'The current version has not been set up yet',
    '只能重新生成第一个版本': 'Only the first version can be regenerated.',
    '没有设置父版本': 'Parent version has not been set up yet',
    '版本历史记录无效': 'Invalid version history record',
    'AI网页复制器': 'AI web page replicator',
    '生成': 'Generate',
    'OpenAI API 目前已关闭, 30 分钟或更晚后重试, 我们对不便表示抱歉': 'OpenAI API is currently down, try again in 30 minutes or later, we apologize for the inconvenience',
    '从视频生成代码可能需要 3-4 分钟, 我们进行多次传递以获得最佳结果, 请耐心等待': 'Code generation from videos may take 3-4 minutes. We run multiple passes to achieve the best result. Please be patient',
    '取消': 'cancel',
    '包括当前版本的屏幕截图吗？': 'Include screenshots of the current version?',
    '更新': 'Update',
    '重新生成': 'Regenerate',
    '原始视频': 'Original Video',
    '原始截图': 'Original Screenshot',
    '告诉AI要改变什么': 'Tell AI what to change',
    '重置': 'Reset',
    '下载': 'Download',
    '桌面端': 'Desktop',
    '移动端': 'Mobile',
    '代码': 'Code',
    '选择': 'Select',
    '账户凭证丢失，请': 'Account credentials lost, please',
    '该工具已禁用/删除': 'The tool has been disabled/deleted',
    '网络错误，请稍后重试': 'Network error, please try again later',
    '账户余额不足，创建属于自己的工具': 'Insufficient account balance, create your own tool',
    '账户总额度已达上限': 'Total account limit reached',
    '账户日额度已达上限': 'Daily account limit reached',
    '当前无可用通道': 'There are currently no available channels',
    '不支持当前API功能': 'Current API function not supported',
    '代码生成已取消': 'Code generation has been canceled',
    '代码生成出错': 'Code generation error',
    '请输入代码': 'Please enter code',
    '请选择你的HTML结构': 'Please select your HTML structure',
    '导入代码': 'Import code',
    '输入HTML代码': 'Enter HTML code',
    '确保您导入的代码是有效的 HTML': `Ensure the code you're importing is a valid HTML.`,
    '结构': 'Stack',
    '导入': 'Import',
    '编码中...': 'Coding in progress...',
    '获得更好结果的技巧': 'Tips for better results',
    '关于AI网页复制器': 'About AI web page replicator',
    '设置': 'Settings',
    'DALL-E 占位符图像生成': 'DALL-E Placeholder Image Generation',
    '它更有趣, 但如果你想省钱, 就关掉它': 'More fun with it but if you want to save money, turn it off.',
    '代码编辑器主题 - 需要刷新页面才能更新': 'Code Editor Theme - requires page refresh to update',
    '保存': 'Save',
    '已复制至剪切板': 'Copied to clipboard',
    '复制代码': 'Copy Code',
    '打开': 'Open',
    '将屏幕截图拖放到此处或单击上传': 'Drag & drop a screenshot here or click to upload',
    '新!': 'New!',
    '上传屏幕录像': 'Upload a screen recording',
    'AI模型': 'AI Model',
    '版本': 'Versions',
    '请等待代码生成完成后再查看旧版本': 'Please wait for code generation to complete before viewing an older version.',
    '父版本': 'Parent version',
    '切换': 'Toggle',
    '该免费工具在本小时的额度已达上限,请访问': "This free tool limit for this hour has been reached, please visit",
    '生成属于自己的工具': 'Generate your own tool',
    '新加坡Prompt大赛冠军框架,一键将简单任务拆解,分析,并生成结构化提示词。': 'Singapore Prompt Contest Champion Framework: Break down simple tasks with a single click, analyze, and generate structured prompts.',
    '根据LangGPT框架优化,将简单任务拆解成复杂的工作流,并生成结构化提示词。': 'Based on the LangGPT framework optimization, simple tasks are disassembled into complex workflows and structured prompts are generated.',
    '将用户输入的画面描述拆解为镜头、光线、主体、背景、风格和氛围六个要素，进行补充和完善，生成高质量的绘画提示词。': 'Deconstruct user input scene descriptions into six elements: camera, lighting, subject, background, style, and atmosphere. Supplement and refine them to generate high-quality drawing prompts.',
    '清华大学和上海AI实验室提出的提示词优化方法。': 'Prompt optimization method proposed by Tsinghua University and Shanghai AI Lab.',
    '通过模拟解决问题的思考过程来提高模型生成内容的质量和相关性。': 'Improve the quality and relevance of model generated content by simulating the problem-solving process.',
    'Google Deepmind最新研究，变分规划提升Prompt。': 'Latest research from Google DeepMind: Variational planning enhances prompting.',
    '利用马尔可夫决策过程进行提示词优化。': 'Optimize prompts using Markov decision processes.',
    '卡内基梅隆大学最新研究，让提示词递归内省。': "Carnegie Mellon University's latest research, recursive introspection of prompts.",
    '微软最新的研究，通过自动优化你的指令数据集来提升你的Prompt能力。': `Microsoft's latest research improves your prompt capabilities by automatically optimizing your command data set.`,
    '请输入内容！': 'Please enter the content!',
    '请输入需要修改的点！': 'Please enter the points that need to be modified!',
    '复制成功 !': 'Copy successful!',
    '请输入您的想法，例如：太空人骑着彩虹独角兽': 'Please input your thoughts, for example: an astronaut riding a rainbow unicorn',
    '请输入您的任务,例如:写一篇宣传AI的小红书': 'Please enter your task, for example: write a REDnote post to promote AI',
    '模仿o1遵循结构化思考、分步推理、持续反思和调整策略的提示词': 'Imitating o1 follows the prompts of structured thinking, step-by-step reasoning, continuous reflection, and adjustment strategies',
    '正在生成，请耐心等待...': 'Generating, please be patient...',
    'CO-STAR结构': 'CO-STAR structure',
    'CRISPE结构': 'CRISPE structure',
    'AI绘画提示词': 'AI drawing prompts',
    'Meta Prompting': 'Meta Prompting',
    'CoT思维链': 'CoT chain of thought',
    '变分法': 'Variational method',
    'Q*': 'Q*',
    'RISE': 'RISE',
    'o1-style': 'o1-style',
    '微软优化法': 'Microsoft Optimization Method',
    '回退': 'Back',
    '请提出需要修改的点': 'Please indicate the points that need to be modified',
    '修改中...': 'Modifying...',
    '修改': 'Modify',
    '复制': 'Copy',
    '正在测试中，请耐心等待...': 'Testing in progress, please wait patiently...',
    '测试': 'Test',
    '测试模型为': 'The test model is',
    '选择一张图片': 'Select an image',
    '或': 'or',
    '上传图片大小不能超过5M': 'The size of the uploaded image cannot exceed 5M',
    '暂不支持当前图片格式': 'The current image format is not supported',
    '自定义': 'custom',
    '自定义提示词优化指令': 'Custom prompt optimization command',
    '编辑提示词优化指令': 'Edit prompt optimization command',
    '提示词优化指令': 'Prompt optimization command',
    '请输入提示词优化指令': 'Please enter the prompt optimization command',
    '你可以使用“{input}”作为占位符替换输入的任务，如果没有指定，则输入的任务会被追加到末尾。': `You can use "{input}" as a placeholder to replace the input task. If not specified, the input task will be appended to the end.`,
    '提示词优化指令为空，请先编辑优化指令！': 'The prompt optimization command is empty, please edit the optimization command first!',
    'OpenAI优化法': 'OpenAI Optimization Method',
    'OpenAI官方开源的提示词优化方法': `OpenAI's official open-source method for optimizing prompt words`,
    "Claude优化法": 'Claude optimization method',
    "Claude官方开源的提示词优化方法": "Claude's official open-source method for optimizing prompt words"
  },
  "japanese": {
    '记住分享码': '共有コードを記憶',
    '重新登录': '再ログイン',
    '确认': '確認',
    '更多请访问': '詳細は以下のリンクをご参照ください',
    '请输入分享码': '共有コードを入力してください',
    '创建者开启了验证, 请在下方填入分享码': '作成者が認証を有効にしていますので、下のフィールドに共有コードを入力してください',
    '需要分享码': '共有コードが必要です',
    '搜索工具已删除': '検索ツールが削除されました',
    '搜索工具已禁用': '検索ツールが無効になっています',
    '分享码错误': '共有コードが間違っています',
    '未知错误': '不明なエラー',
    '网络错误': 'ネットワークエラー',
    '请联系': 'お問い合わせ',
    '客服': 'サポート',
    '没有设置当前版本': '現在のバージョンが設定されていません',
    '只能重新生成第一个版本': '最初のバージョンしか再生成できません',
    '没有设置父版本': '親バージョンが設定されていません',
    '版本历史记录无效': 'バージョン履歴が無効です',
    'AI网页复制器': 'AIウェブコピー生成器',
    '生成': '生成',
    'OpenAI API 目前已关闭, 30 分钟或更晚后重试, 我们对不便表示抱歉': 'OpenAI APIは現在停止中です。30分後またはそれ以降に再試行してください。ご不便をおかけして申し訳ございません',
    '从视频生成代码可能需要 3-4 分钟, 我们进行多次传递以获得最佳结果, 请耐心等待': '動画からコードを生成するには3〜4分かかる場合があります。最良の結果を得るために複数回試行するので、しばらくお待ちください',
    '取消': 'キャンセル',
    '包括当前版本的屏幕截图吗？': '現在のバージョンのスクリーンショットを含みますか？',
    '更新': '更新',
    '重新生成': '再生成',
    '原始视频': '元の動画',
    '原始截图': '元のスクリーンショット',
    '告诉AI要改变什么': 'AIに変更点を伝える',
    '重置': 'リセット',
    '下载': 'ダウンロード',
    '桌面端': 'デスクトップ版',
    '移动端': 'モバイル版',
    '代码': 'コード',
    '选择': '選択',
    '账户凭证丢失，请': 'アカウントの資格情報が失われました',
    '该工具已禁用/删除': 'このツールは無効/削除されました',
    '网络错误，请稍后重试': 'ネットワークエラーが発生しました。後でもう一度お試しください',
    '账户余额不足，创建属于自己的工具': 'アカウント残高が不足しています。独自のツールを作成してください',
    '账户总额度已达上限': 'アカウントの総限度額に達しました',
    '账户日额度已达上限': 'アカウントの日次限度額に達しました',
    '当前无可用通道': '現在利用可能なチャネルがありません',
    '不支持当前API功能': 'このAPI機能はサポートされていません',
    '代码生成已取消': 'コード生成がキャンセルされました',
    '代码生成出错': 'コード生成エラー',
    '请输入代码': 'コードを入力してください',
    '请选择你的HTML结构': 'HTML構造を選択してください',
    '导入代码': 'コードをインポート',
    '输入HTML代码': 'HTMLコードを入力してください',
    '确保您导入的代码是有效的 HTML': 'インポートするコードが有効なHTMLであることを確認してください',
    '结构': '構造',
    '导入': 'インポート',
    '编码中...': 'コーディング中...',
    '获得更好结果的技巧': 'より良い結果を得るためのヒント',
    '关于AI网页复制器': 'AIウェブコピー生成器について',
    '设置': '設定',
    'DALL-E 占位符图像生成': 'DALL-Eのプレースホルダー画像生成',
    '它更有趣, 但如果你想省钱, 就关掉它': 'それは楽しいですが、節約したい場合はオフにしてください',
    '代码编辑器主题 - 需要刷新页面才能更新': 'コードエディターのテーマ - 更新するにはページを再読み込みする必要があります',
    '保存': '保存',
    '已复制至剪切板': 'クリップボードにコピーしました',
    '复制代码': 'コードをコピー',
    '打开': '開く',
    '将屏幕截图拖放到此处或单击上传': 'ここにスクリーンショットをドラッグするか、クリックしてアップロードしてください',
    '新!': '新規！',
    '上传屏幕录像': 'スクリーン録画をアップロード',
    'AI模型': 'AIモデル',
    '版本': 'バージョン',
    '请等待代码生成完成后再查看旧版本': 'コード生成が完了するまで、以前のバージョンを表示しないでください',
    '父版本': '親バージョン',
    '切换': '切り替え',
    '该免费工具在本小时的额度已达上限,请访问': 'この無料ツールは今時間の限度に達しました。詳細は以下のリンクをご参照ください',
    '生成属于自己的工具': '独自のツールを生成',
    '新加坡Prompt大赛冠军框架,一键将简单任务拆解,分析,并生成结构化提示词。': 'シンガポールPromptコンテストの優勝フレームワーク。一クリックで簡単なタスクを分解し、分析し、構造化された提示詞を生成します。',
    '根据LangGPT框架优化,将简单任务拆解成复杂的工作流,并生成结构化提示词。': 'LangGPTフレームワークに基づいて、簡単なタスクを複雑なワークフローに分解し、構造化された提示詞を生成します。',
    '将用户输入的画面描述拆解为镜头、光线、主体、背景、风格和氛围六个要素，进行补充和完善，生成高质量的绘画提示词。': 'ユーザーが入力した画面の説明を、カメラアングル、光、主体、背景、スタイル、雰囲気の6つの要素に分解し、補足して高品質な絵画の提示詞を生成します。',
    '清华大学和上海AI实验室提出的提示词优化方法。': '清華大学と上海AIラボが提案した提示詞最適化方法。',
    '通过模拟解决问题的思考过程来提高模型生成内容的质量和相关性。': '問題解決の思考プロセスをシミュレートすることで、モデル生成コンテンツの質と関連性を向上させます。',
    'Google Deepmind最新研究，变分规划提升Prompt。': 'Google Deepmindの最新研究、変分法計画によるPromptの向上。',
    '利用马尔可夫决策过程进行提示词优化。': 'マルコフ決定過程を活用した提示詞最適化。',
    '卡内基梅隆大学最新研究，让提示词递归内省。': 'カーネギーメロン大学の最新研究、提示詞を再帰的に内省させる。',
    '微软最新的研究，通过自动优化你的指令数据集来提升你的Prompt能力。': 'Microsoftの最新研究、自動的に命令データセットを最適化してPromptの能力を向上させる。',
    '请输入内容！': '内容を入力してください！',
    '请输入需要修改的点！': '変更点を入力してください！',
    '复制成功 !': 'コピー成功！',
    '请输入您的想法，例如：太空人骑着彩虹独角兽': 'アイデアを入力してください。例：「宇宙飛行士が虹色のユニコーンに乗っている」',
    '请输入您的任务,例如:写一篇宣传AI的小红书': 'タスクを入力してください。例：「AIを宣伝するためのXiaohongshuの記事を書く」',
    '模仿o1遵循结构化思考、分步推理、持续反思和调整策略的提示词': 'o 1を模倣した構造的思考、段階的推論、継続的な反省と調整戦略に従うためのヒントワード',
    '正在生成，请耐心等待...': '生成中です。しばらくお待ちください...',
    'CO-STAR结构': 'CO−STAR構造',
    'CRISPE结构': 'CRISPE構造',
    'AI绘画提示词': 'AI絵画提示語',
    'Meta Prompting': 'Meta Prompting',
    'CoT思维链': 'CoT思考の連鎖',
    '变分法': '変分法',
    'Q*': 'Q*',
    'RISE': 'RISE',
    'o1-style': 'o1-style',
    '微软优化法': 'Microsoftの最適化法',
    '回退': '戻る',
    '请提出需要修改的点': '変更点を提示してください',
    '修改中...': '変更中...',
    '修改': '変更',
    '复制': 'コピー',
    '正在测试中，请耐心等待...': 'テスト中です。しばらくお待ちください...',
    '测试': 'テスト',
    '测试模型为': 'テストモデルは',
    '选择一张图片': '画像のアップロードサイズは5MB以下にしてください',
    '或': 'または',
    '暂不支持当前图片格式': '現在、この画像形式はサポートされていません',
    '自定义': 'カスタム',
    '自定义提示词优化指令': 'カスタム提示詞最適化指示',
    '编辑提示词优化指令': '提示詞最適化指示を編集',
    '提示词优化指令': '提示詞最適化指示',
    '请输入提示词优化指令': '提示詞最適化指示を入力してください',
    '你可以使用“{input}”作为占位符替换输入的任务，如果没有指定，则输入的任务会被追加到末尾。': '「{input}」をプレースホルダーとして使用してタスクを入力できます。指定がない場合は、タスクが末尾に追加されます。',
    '提示词优化指令为空，请先编辑优化指令！': '提示詞最適化指示が空です。まず指示を編集してください！',
    'OpenAI优化法': 'OpenAI最適化法',
    'OpenAI官方开源的提示词优化方法': 'OpenAI公式オープンソースの提示語最適化方法',
    "Claude优化法": 'claude最適化法',
    "Claude官方开源的提示词优化方法": "Claude公式オープンソースの提示語最適化方法"
  }
}









