export default function PoweredBy({ language }: { language: 'chinese' | 'english' | 'japanese' }) {
  const href = import.meta.env.VITE_APP_REGION ?
    import.meta.env.VITE_APP_OFFICIAL_WEBSITE_URL_GLOBAL :
    import.meta.env.VITE_APP_OFFICIAL_WEBSITE_URL_CHINA
  return (
    <>
      <div
        className="flex justify-center items-center gap-1 mb-2"
        style={{ color: "rgb(102, 102, 102)", fontSize: "12px" }}
      >
        Powered By
        <a target="_blank" href={href}>
          <img
            className="object-contain"
            src="https://file.302.ai/gpt/imgs/91f7b86c2cf921f61e8cf9dc7b1ec5ee.png"
            alt="gpt302"
            width="55"
          />
        </a>
      </div>
      <div className="text-center mb-1" style={{ color: "rgb(200, 200, 200)", fontSize: "12px" }}>
        {language === 'chinese' ? "内容由AI生成，仅供参考" : language === 'japanese' ? 'コンテンツは参照用にAIによって生成される' : "Content generated by AI, for reference only"}
      </div>
    </>
  );
}
